# coding: utf-8

"""
    Oktawave API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyodk
from pyodk.models.opn import Opn  # noqa: E501
from pyodk.rest import ApiException


class TestOpn(unittest.TestCase):
    """Opn unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOpn(self):
        """Test Opn"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyodk.models.opn.Opn()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
