# coding: utf-8

"""
    Oktawave API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyodk
from pyodk.api.oci_templates_api import OCITemplatesApi  # noqa: E501
from pyodk.rest import ApiException


class TestOCITemplatesApi(unittest.TestCase):
    """OCITemplatesApi unit test stubs"""

    def setUp(self):
        self.api = pyodk.api.oci_templates_api.OCITemplatesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_templates_delete(self):
        """Test case for templates_delete

        Deletes template  # noqa: E501
        """
        pass

    def test_templates_get(self):
        """Test case for templates_get

        Returns templates list  # noqa: E501
        """
        pass

    def test_templates_get_0(self):
        """Test case for templates_get_0

        Returns template by identifier  # noqa: E501
        """
        pass

    def test_templates_put(self):
        """Test case for templates_put

        Updates template  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
