# coding: utf-8

"""
    Oktawave API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyodk
from pyodk.models.create_update_health_check_imap_command import CreateUpdateHealthCheckImapCommand  # noqa: E501
from pyodk.rest import ApiException


class TestCreateUpdateHealthCheckImapCommand(unittest.TestCase):
    """CreateUpdateHealthCheckImapCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateUpdateHealthCheckImapCommand(self):
        """Test CreateUpdateHealthCheckImapCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyodk.models.create_update_health_check_imap_command.CreateUpdateHealthCheckImapCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
