# coding: utf-8

"""
    Oktawave API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyodk
from pyodk.models.base_resource import BaseResource  # noqa: E501
from pyodk.rest import ApiException


class TestBaseResource(unittest.TestCase):
    """BaseResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBaseResource(self):
        """Test BaseResource"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyodk.models.base_resource.BaseResource()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
