# coding: utf-8

"""
    Oktawave API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyodk
from pyodk.api.subregions_api import SubregionsApi  # noqa: E501
from pyodk.rest import ApiException


class TestSubregionsApi(unittest.TestCase):
    """SubregionsApi unit test stubs"""

    def setUp(self):
        self.api = pyodk.api.subregions_api.SubregionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_subregions_get(self):
        """Test case for subregions_get

        Gets subregions  # noqa: E501
        """
        pass

    def test_subregions_get_0(self):
        """Test case for subregions_get_0

        Gets subregion  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
