# coding: utf-8

"""
    Oktawave API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyodk
from pyodk.api.oci_events_api import OCIEventsApi  # noqa: E501
from pyodk.rest import ApiException


class TestOCIEventsApi(unittest.TestCase):
    """OCIEventsApi unit test stubs"""

    def setUp(self):
        self.api = pyodk.api.oci_events_api.OCIEventsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_events_delete(self):
        """Test case for events_delete

        Deletes event  # noqa: E501
        """
        pass

    def test_events_get_event(self):
        """Test case for events_get_event

        Returns instance event  # noqa: E501
        """
        pass

    def test_events_get_events(self):
        """Test case for events_get_events

        Returns all instances events  # noqa: E501
        """
        pass

    def test_instances_delete_events(self):
        """Test case for instances_delete_events

        Deletes instance events  # noqa: E501
        """
        pass

    def test_instances_get_events(self):
        """Test case for instances_get_events

        Returns instance events  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
