# coding: utf-8

"""
    Oktawave API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyodk
from pyodk.api.oci_autoscaler_api import OCIAutoscalerApi  # noqa: E501
from pyodk.rest import ApiException


class TestOCIAutoscalerApi(unittest.TestCase):
    """OCIAutoscalerApi unit test stubs"""

    def setUp(self):
        self.api = pyodk.api.oci_autoscaler_api.OCIAutoscalerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_instances_disable_instance_autoscaler(self):
        """Test case for instances_disable_instance_autoscaler

        Disables autoscaling for instance  # noqa: E501
        """
        pass

    def test_instances_enable_instance_autoscaler(self):
        """Test case for instances_enable_instance_autoscaler

        Enables autoscaling for instance  # noqa: E501
        """
        pass

    def test_instances_get_autoscaler(self):
        """Test case for instances_get_autoscaler

        Returns instace autoscaler configuration  # noqa: E501
        """
        pass

    def test_instances_update_autoscaler(self):
        """Test case for instances_update_autoscaler

        Updates instance autoscaler configuration  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
