# coding: utf-8

"""
    Oktawave API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyodk
from pyodk.models.exports_search_params import ExportsSearchParams  # noqa: E501
from pyodk.rest import ApiException


class TestExportsSearchParams(unittest.TestCase):
    """ExportsSearchParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExportsSearchParams(self):
        """Test ExportsSearchParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyodk.models.exports_search_params.ExportsSearchParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
