# coding: utf-8

"""
    Oktawave API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyodk
from pyodk.models.create_ssh_key_command import CreateSshKeyCommand  # noqa: E501
from pyodk.rest import ApiException


class TestCreateSshKeyCommand(unittest.TestCase):
    """CreateSshKeyCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateSshKeyCommand(self):
        """Test CreateSshKeyCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyodk.models.create_ssh_key_command.CreateSshKeyCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
