# coding: utf-8

"""
    Oktawave API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyodk
from pyodk.models.monitoring_sensor import MonitoringSensor  # noqa: E501
from pyodk.rest import ApiException


class TestMonitoringSensor(unittest.TestCase):
    """MonitoringSensor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMonitoringSensor(self):
        """Test MonitoringSensor"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyodk.models.monitoring_sensor.MonitoringSensor()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
