# coding: utf-8

"""
    Oktawave API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyodk
from pyodk.models.access_data import AccessData  # noqa: E501
from pyodk.rest import ApiException


class TestAccessData(unittest.TestCase):
    """AccessData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccessData(self):
        """Test AccessData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyodk.models.access_data.AccessData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
