# coding: utf-8

"""
    Oktawave API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import pyodk
from pyodk.models.autoscaler import Autoscaler  # noqa: E501
from pyodk.rest import ApiException


class TestAutoscaler(unittest.TestCase):
    """Autoscaler unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAutoscaler(self):
        """Test Autoscaler"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pyodk.models.autoscaler.Autoscaler()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
