# coding: utf-8

"""
    Oktawave API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from pyodk.configuration import Configuration


class ChangeContainerServiceStateCommand(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ip_address': 'str',
        'port': 'int',
        'enabled': 'bool',
        'graceful': 'bool'
    }

    attribute_map = {
        'ip_address': 'IpAddress',
        'port': 'Port',
        'enabled': 'Enabled',
        'graceful': 'Graceful'
    }

    def __init__(self, ip_address=None, port=None, enabled=None, graceful=None, _configuration=None):  # noqa: E501
        """ChangeContainerServiceStateCommand - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._ip_address = None
        self._port = None
        self._enabled = None
        self._graceful = None
        self.discriminator = None

        self.ip_address = ip_address
        self.port = port
        self.enabled = enabled
        if graceful is not None:
            self.graceful = graceful

    @property
    def ip_address(self):
        """Gets the ip_address of this ChangeContainerServiceStateCommand.  # noqa: E501

        Service ip address  # noqa: E501

        :return: The ip_address of this ChangeContainerServiceStateCommand.  # noqa: E501
        :rtype: str
        """
        return self._ip_address

    @ip_address.setter
    def ip_address(self, ip_address):
        """Sets the ip_address of this ChangeContainerServiceStateCommand.

        Service ip address  # noqa: E501

        :param ip_address: The ip_address of this ChangeContainerServiceStateCommand.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and ip_address is None:
            raise ValueError("Invalid value for `ip_address`, must not be `None`")  # noqa: E501
        if (self._configuration.client_side_validation and
                ip_address is not None and not re.search(r'^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$', ip_address)):  # noqa: E501
            raise ValueError(r"Invalid value for `ip_address`, must be a follow pattern or equal to `/^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$/`")  # noqa: E501

        self._ip_address = ip_address

    @property
    def port(self):
        """Gets the port of this ChangeContainerServiceStateCommand.  # noqa: E501

        Service port  # noqa: E501

        :return: The port of this ChangeContainerServiceStateCommand.  # noqa: E501
        :rtype: int
        """
        return self._port

    @port.setter
    def port(self, port):
        """Sets the port of this ChangeContainerServiceStateCommand.

        Service port  # noqa: E501

        :param port: The port of this ChangeContainerServiceStateCommand.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and port is None:
            raise ValueError("Invalid value for `port`, must not be `None`")  # noqa: E501

        self._port = port

    @property
    def enabled(self):
        """Gets the enabled of this ChangeContainerServiceStateCommand.  # noqa: E501

        Target state  # noqa: E501

        :return: The enabled of this ChangeContainerServiceStateCommand.  # noqa: E501
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this ChangeContainerServiceStateCommand.

        Target state  # noqa: E501

        :param enabled: The enabled of this ChangeContainerServiceStateCommand.  # noqa: E501
        :type: bool
        """
        if self._configuration.client_side_validation and enabled is None:
            raise ValueError("Invalid value for `enabled`, must not be `None`")  # noqa: E501

        self._enabled = enabled

    @property
    def graceful(self):
        """Gets the graceful of this ChangeContainerServiceStateCommand.  # noqa: E501

        If true - waits for closing all open connections on specific service before disabling  # noqa: E501

        :return: The graceful of this ChangeContainerServiceStateCommand.  # noqa: E501
        :rtype: bool
        """
        return self._graceful

    @graceful.setter
    def graceful(self, graceful):
        """Sets the graceful of this ChangeContainerServiceStateCommand.

        If true - waits for closing all open connections on specific service before disabling  # noqa: E501

        :param graceful: The graceful of this ChangeContainerServiceStateCommand.  # noqa: E501
        :type: bool
        """

        self._graceful = graceful

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ChangeContainerServiceStateCommand, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ChangeContainerServiceStateCommand):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ChangeContainerServiceStateCommand):
            return True

        return self.to_dict() != other.to_dict()
