# coding: utf-8

"""
    Oktawave API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from pyodk.configuration import Configuration


class DiskConnection(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'instance': 'BaseResource',
        'controller': 'int',
        'slot': 'int',
        'is_system_disk': 'bool'
    }

    attribute_map = {
        'instance': 'Instance',
        'controller': 'Controller',
        'slot': 'Slot',
        'is_system_disk': 'IsSystemDisk'
    }

    def __init__(self, instance=None, controller=None, slot=None, is_system_disk=None, _configuration=None):  # noqa: E501
        """DiskConnection - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._instance = None
        self._controller = None
        self._slot = None
        self._is_system_disk = None
        self.discriminator = None

        if instance is not None:
            self.instance = instance
        if controller is not None:
            self.controller = controller
        if slot is not None:
            self.slot = slot
        if is_system_disk is not None:
            self.is_system_disk = is_system_disk

    @property
    def instance(self):
        """Gets the instance of this DiskConnection.  # noqa: E501

        Instance  # noqa: E501

        :return: The instance of this DiskConnection.  # noqa: E501
        :rtype: BaseResource
        """
        return self._instance

    @instance.setter
    def instance(self, instance):
        """Sets the instance of this DiskConnection.

        Instance  # noqa: E501

        :param instance: The instance of this DiskConnection.  # noqa: E501
        :type: BaseResource
        """

        self._instance = instance

    @property
    def controller(self):
        """Gets the controller of this DiskConnection.  # noqa: E501

        Controller  # noqa: E501

        :return: The controller of this DiskConnection.  # noqa: E501
        :rtype: int
        """
        return self._controller

    @controller.setter
    def controller(self, controller):
        """Sets the controller of this DiskConnection.

        Controller  # noqa: E501

        :param controller: The controller of this DiskConnection.  # noqa: E501
        :type: int
        """

        self._controller = controller

    @property
    def slot(self):
        """Gets the slot of this DiskConnection.  # noqa: E501

        Slot  # noqa: E501

        :return: The slot of this DiskConnection.  # noqa: E501
        :rtype: int
        """
        return self._slot

    @slot.setter
    def slot(self, slot):
        """Sets the slot of this DiskConnection.

        Slot  # noqa: E501

        :param slot: The slot of this DiskConnection.  # noqa: E501
        :type: int
        """

        self._slot = slot

    @property
    def is_system_disk(self):
        """Gets the is_system_disk of this DiskConnection.  # noqa: E501

        If is system disk  # noqa: E501

        :return: The is_system_disk of this DiskConnection.  # noqa: E501
        :rtype: bool
        """
        return self._is_system_disk

    @is_system_disk.setter
    def is_system_disk(self, is_system_disk):
        """Sets the is_system_disk of this DiskConnection.

        If is system disk  # noqa: E501

        :param is_system_disk: The is_system_disk of this DiskConnection.  # noqa: E501
        :type: bool
        """

        self._is_system_disk = is_system_disk

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DiskConnection, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DiskConnection):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DiskConnection):
            return True

        return self.to_dict() != other.to_dict()
