# coding: utf-8

"""
    Oktawave API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from pyodk.configuration import Configuration


class GroupAutoscaler(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'expansion_type': 'DictionaryItem',
        'minimum_instance_number': 'int',
        'maximum_instance_number': 'int',
        'instances': 'list[GroupAutoscalerInstance]'
    }

    attribute_map = {
        'expansion_type': 'ExpansionType',
        'minimum_instance_number': 'MinimumInstanceNumber',
        'maximum_instance_number': 'MaximumInstanceNumber',
        'instances': 'Instances'
    }

    def __init__(self, expansion_type=None, minimum_instance_number=None, maximum_instance_number=None, instances=None, _configuration=None):  # noqa: E501
        """GroupAutoscaler - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._expansion_type = None
        self._minimum_instance_number = None
        self._maximum_instance_number = None
        self._instances = None
        self.discriminator = None

        if expansion_type is not None:
            self.expansion_type = expansion_type
        if minimum_instance_number is not None:
            self.minimum_instance_number = minimum_instance_number
        if maximum_instance_number is not None:
            self.maximum_instance_number = maximum_instance_number
        if instances is not None:
            self.instances = instances

    @property
    def expansion_type(self):
        """Gets the expansion_type of this GroupAutoscaler.  # noqa: E501

        Expansion type  # noqa: E501

        :return: The expansion_type of this GroupAutoscaler.  # noqa: E501
        :rtype: DictionaryItem
        """
        return self._expansion_type

    @expansion_type.setter
    def expansion_type(self, expansion_type):
        """Sets the expansion_type of this GroupAutoscaler.

        Expansion type  # noqa: E501

        :param expansion_type: The expansion_type of this GroupAutoscaler.  # noqa: E501
        :type: DictionaryItem
        """

        self._expansion_type = expansion_type

    @property
    def minimum_instance_number(self):
        """Gets the minimum_instance_number of this GroupAutoscaler.  # noqa: E501

        Minimum instance number in group  # noqa: E501

        :return: The minimum_instance_number of this GroupAutoscaler.  # noqa: E501
        :rtype: int
        """
        return self._minimum_instance_number

    @minimum_instance_number.setter
    def minimum_instance_number(self, minimum_instance_number):
        """Sets the minimum_instance_number of this GroupAutoscaler.

        Minimum instance number in group  # noqa: E501

        :param minimum_instance_number: The minimum_instance_number of this GroupAutoscaler.  # noqa: E501
        :type: int
        """

        self._minimum_instance_number = minimum_instance_number

    @property
    def maximum_instance_number(self):
        """Gets the maximum_instance_number of this GroupAutoscaler.  # noqa: E501

        Minimum instance number in group  # noqa: E501

        :return: The maximum_instance_number of this GroupAutoscaler.  # noqa: E501
        :rtype: int
        """
        return self._maximum_instance_number

    @maximum_instance_number.setter
    def maximum_instance_number(self, maximum_instance_number):
        """Sets the maximum_instance_number of this GroupAutoscaler.

        Minimum instance number in group  # noqa: E501

        :param maximum_instance_number: The maximum_instance_number of this GroupAutoscaler.  # noqa: E501
        :type: int
        """

        self._maximum_instance_number = maximum_instance_number

    @property
    def instances(self):
        """Gets the instances of this GroupAutoscaler.  # noqa: E501

        Instances to scaling  # noqa: E501

        :return: The instances of this GroupAutoscaler.  # noqa: E501
        :rtype: list[GroupAutoscalerInstance]
        """
        return self._instances

    @instances.setter
    def instances(self, instances):
        """Sets the instances of this GroupAutoscaler.

        Instances to scaling  # noqa: E501

        :param instances: The instances of this GroupAutoscaler.  # noqa: E501
        :type: list[GroupAutoscalerInstance]
        """

        self._instances = instances

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GroupAutoscaler, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GroupAutoscaler):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GroupAutoscaler):
            return True

        return self.to_dict() != other.to_dict()
