# coding: utf-8

"""
    Oktawave API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from pyodk.configuration import Configuration


class InstancesSearchParams(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'template_type_id': 'int',
        'is_turned_on': 'bool',
        'subregion_id': 'int',
        'type_id': 'int',
        'query': 'str',
        'page_size': 'int',
        'page_number': 'int',
        'order_by': 'str',
        'sort_expression': 'str',
        'sort_direction': 'str'
    }

    attribute_map = {
        'template_type_id': 'TemplateTypeId',
        'is_turned_on': 'IsTurnedOn',
        'subregion_id': 'SubregionId',
        'type_id': 'TypeId',
        'query': 'Query',
        'page_size': 'PageSize',
        'page_number': 'PageNumber',
        'order_by': 'OrderBy',
        'sort_expression': 'SortExpression',
        'sort_direction': 'SortDirection'
    }

    def __init__(self, template_type_id=None, is_turned_on=None, subregion_id=None, type_id=None, query=None, page_size=None, page_number=None, order_by=None, sort_expression=None, sort_direction=None, _configuration=None):  # noqa: E501
        """InstancesSearchParams - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._template_type_id = None
        self._is_turned_on = None
        self._subregion_id = None
        self._type_id = None
        self._query = None
        self._page_size = None
        self._page_number = None
        self._order_by = None
        self._sort_expression = None
        self._sort_direction = None
        self.discriminator = None

        if template_type_id is not None:
            self.template_type_id = template_type_id
        if is_turned_on is not None:
            self.is_turned_on = is_turned_on
        if subregion_id is not None:
            self.subregion_id = subregion_id
        if type_id is not None:
            self.type_id = type_id
        if query is not None:
            self.query = query
        if page_size is not None:
            self.page_size = page_size
        if page_number is not None:
            self.page_number = page_number
        if order_by is not None:
            self.order_by = order_by
        if sort_expression is not None:
            self.sort_expression = sort_expression
        if sort_direction is not None:
            self.sort_direction = sort_direction

    @property
    def template_type_id(self):
        """Gets the template_type_id of this InstancesSearchParams.  # noqa: E501

        Template type id eg marketplace, oci instance  # noqa: E501

        :return: The template_type_id of this InstancesSearchParams.  # noqa: E501
        :rtype: int
        """
        return self._template_type_id

    @template_type_id.setter
    def template_type_id(self, template_type_id):
        """Sets the template_type_id of this InstancesSearchParams.

        Template type id eg marketplace, oci instance  # noqa: E501

        :param template_type_id: The template_type_id of this InstancesSearchParams.  # noqa: E501
        :type: int
        """

        self._template_type_id = template_type_id

    @property
    def is_turned_on(self):
        """Gets the is_turned_on of this InstancesSearchParams.  # noqa: E501

        Indicates wether an instance is turned on  # noqa: E501

        :return: The is_turned_on of this InstancesSearchParams.  # noqa: E501
        :rtype: bool
        """
        return self._is_turned_on

    @is_turned_on.setter
    def is_turned_on(self, is_turned_on):
        """Sets the is_turned_on of this InstancesSearchParams.

        Indicates wether an instance is turned on  # noqa: E501

        :param is_turned_on: The is_turned_on of this InstancesSearchParams.  # noqa: E501
        :type: bool
        """

        self._is_turned_on = is_turned_on

    @property
    def subregion_id(self):
        """Gets the subregion_id of this InstancesSearchParams.  # noqa: E501

        Subregion Id  # noqa: E501

        :return: The subregion_id of this InstancesSearchParams.  # noqa: E501
        :rtype: int
        """
        return self._subregion_id

    @subregion_id.setter
    def subregion_id(self, subregion_id):
        """Sets the subregion_id of this InstancesSearchParams.

        Subregion Id  # noqa: E501

        :param subregion_id: The subregion_id of this InstancesSearchParams.  # noqa: E501
        :type: int
        """

        self._subregion_id = subregion_id

    @property
    def type_id(self):
        """Gets the type_id of this InstancesSearchParams.  # noqa: E501

        Type Id  # noqa: E501

        :return: The type_id of this InstancesSearchParams.  # noqa: E501
        :rtype: int
        """
        return self._type_id

    @type_id.setter
    def type_id(self, type_id):
        """Sets the type_id of this InstancesSearchParams.

        Type Id  # noqa: E501

        :param type_id: The type_id of this InstancesSearchParams.  # noqa: E501
        :type: int
        """

        self._type_id = type_id

    @property
    def query(self):
        """Gets the query of this InstancesSearchParams.  # noqa: E501

        Query  # noqa: E501

        :return: The query of this InstancesSearchParams.  # noqa: E501
        :rtype: str
        """
        return self._query

    @query.setter
    def query(self, query):
        """Sets the query of this InstancesSearchParams.

        Query  # noqa: E501

        :param query: The query of this InstancesSearchParams.  # noqa: E501
        :type: str
        """

        self._query = query

    @property
    def page_size(self):
        """Gets the page_size of this InstancesSearchParams.  # noqa: E501

        Page size  # noqa: E501

        :return: The page_size of this InstancesSearchParams.  # noqa: E501
        :rtype: int
        """
        return self._page_size

    @page_size.setter
    def page_size(self, page_size):
        """Sets the page_size of this InstancesSearchParams.

        Page size  # noqa: E501

        :param page_size: The page_size of this InstancesSearchParams.  # noqa: E501
        :type: int
        """

        self._page_size = page_size

    @property
    def page_number(self):
        """Gets the page_number of this InstancesSearchParams.  # noqa: E501

        Page number  # noqa: E501

        :return: The page_number of this InstancesSearchParams.  # noqa: E501
        :rtype: int
        """
        return self._page_number

    @page_number.setter
    def page_number(self, page_number):
        """Sets the page_number of this InstancesSearchParams.

        Page number  # noqa: E501

        :param page_number: The page_number of this InstancesSearchParams.  # noqa: E501
        :type: int
        """

        self._page_number = page_number

    @property
    def order_by(self):
        """Gets the order_by of this InstancesSearchParams.  # noqa: E501

        Order by  # noqa: E501

        :return: The order_by of this InstancesSearchParams.  # noqa: E501
        :rtype: str
        """
        return self._order_by

    @order_by.setter
    def order_by(self, order_by):
        """Sets the order_by of this InstancesSearchParams.

        Order by  # noqa: E501

        :param order_by: The order_by of this InstancesSearchParams.  # noqa: E501
        :type: str
        """

        self._order_by = order_by

    @property
    def sort_expression(self):
        """Gets the sort_expression of this InstancesSearchParams.  # noqa: E501

        Sort expression  # noqa: E501

        :return: The sort_expression of this InstancesSearchParams.  # noqa: E501
        :rtype: str
        """
        return self._sort_expression

    @sort_expression.setter
    def sort_expression(self, sort_expression):
        """Sets the sort_expression of this InstancesSearchParams.

        Sort expression  # noqa: E501

        :param sort_expression: The sort_expression of this InstancesSearchParams.  # noqa: E501
        :type: str
        """

        self._sort_expression = sort_expression

    @property
    def sort_direction(self):
        """Gets the sort_direction of this InstancesSearchParams.  # noqa: E501

        Sort direction  # noqa: E501

        :return: The sort_direction of this InstancesSearchParams.  # noqa: E501
        :rtype: str
        """
        return self._sort_direction

    @sort_direction.setter
    def sort_direction(self, sort_direction):
        """Sets the sort_direction of this InstancesSearchParams.

        Sort direction  # noqa: E501

        :param sort_direction: The sort_direction of this InstancesSearchParams.  # noqa: E501
        :type: str
        """
        allowed_values = ["Descending", "Ascending"]  # noqa: E501
        if (self._configuration.client_side_validation and
                sort_direction not in allowed_values):
            raise ValueError(
                "Invalid value for `sort_direction` ({0}), must be one of {1}"  # noqa: E501
                .format(sort_direction, allowed_values)
            )

        self._sort_direction = sort_direction

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InstancesSearchParams, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InstancesSearchParams):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InstancesSearchParams):
            return True

        return self.to_dict() != other.to_dict()
