# coding: utf-8

"""
    Oktawave API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from pyodk.configuration import Configuration


class NetworkInterface(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'interface_id': 'int',
        'mac_address': 'str',
        'instance': 'NamedResource',
        'opn': 'NamedResource',
        'address': 'str',
        'address_v6': 'str',
        'ip': 'BaseResource',
        'comment': 'str',
        'rev_dns': 'str',
        'rev_dns_v6': 'str',
        'subregion': 'BaseResource',
        'creation_user': 'UserResource'
    }

    attribute_map = {
        'interface_id': 'InterfaceId',
        'mac_address': 'MacAddress',
        'instance': 'Instance',
        'opn': 'Opn',
        'address': 'Address',
        'address_v6': 'AddressV6',
        'ip': 'Ip',
        'comment': 'Comment',
        'rev_dns': 'RevDns',
        'rev_dns_v6': 'RevDnsV6',
        'subregion': 'Subregion',
        'creation_user': 'CreationUser'
    }

    def __init__(self, interface_id=None, mac_address=None, instance=None, opn=None, address=None, address_v6=None, ip=None, comment=None, rev_dns=None, rev_dns_v6=None, subregion=None, creation_user=None, _configuration=None):  # noqa: E501
        """NetworkInterface - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._interface_id = None
        self._mac_address = None
        self._instance = None
        self._opn = None
        self._address = None
        self._address_v6 = None
        self._ip = None
        self._comment = None
        self._rev_dns = None
        self._rev_dns_v6 = None
        self._subregion = None
        self._creation_user = None
        self.discriminator = None

        if interface_id is not None:
            self.interface_id = interface_id
        if mac_address is not None:
            self.mac_address = mac_address
        if instance is not None:
            self.instance = instance
        if opn is not None:
            self.opn = opn
        if address is not None:
            self.address = address
        if address_v6 is not None:
            self.address_v6 = address_v6
        if ip is not None:
            self.ip = ip
        if comment is not None:
            self.comment = comment
        if rev_dns is not None:
            self.rev_dns = rev_dns
        if rev_dns_v6 is not None:
            self.rev_dns_v6 = rev_dns_v6
        if subregion is not None:
            self.subregion = subregion
        if creation_user is not None:
            self.creation_user = creation_user

    @property
    def interface_id(self):
        """Gets the interface_id of this NetworkInterface.  # noqa: E501

        Interface id  # noqa: E501

        :return: The interface_id of this NetworkInterface.  # noqa: E501
        :rtype: int
        """
        return self._interface_id

    @interface_id.setter
    def interface_id(self, interface_id):
        """Sets the interface_id of this NetworkInterface.

        Interface id  # noqa: E501

        :param interface_id: The interface_id of this NetworkInterface.  # noqa: E501
        :type: int
        """

        self._interface_id = interface_id

    @property
    def mac_address(self):
        """Gets the mac_address of this NetworkInterface.  # noqa: E501

        The MAC address of the network card associated with that IP address  # noqa: E501

        :return: The mac_address of this NetworkInterface.  # noqa: E501
        :rtype: str
        """
        return self._mac_address

    @mac_address.setter
    def mac_address(self, mac_address):
        """Sets the mac_address of this NetworkInterface.

        The MAC address of the network card associated with that IP address  # noqa: E501

        :param mac_address: The mac_address of this NetworkInterface.  # noqa: E501
        :type: str
        """

        self._mac_address = mac_address

    @property
    def instance(self):
        """Gets the instance of this NetworkInterface.  # noqa: E501

        Instance  # noqa: E501

        :return: The instance of this NetworkInterface.  # noqa: E501
        :rtype: NamedResource
        """
        return self._instance

    @instance.setter
    def instance(self, instance):
        """Sets the instance of this NetworkInterface.

        Instance  # noqa: E501

        :param instance: The instance of this NetworkInterface.  # noqa: E501
        :type: NamedResource
        """

        self._instance = instance

    @property
    def opn(self):
        """Gets the opn of this NetworkInterface.  # noqa: E501

        OPN  # noqa: E501

        :return: The opn of this NetworkInterface.  # noqa: E501
        :rtype: NamedResource
        """
        return self._opn

    @opn.setter
    def opn(self, opn):
        """Sets the opn of this NetworkInterface.

        OPN  # noqa: E501

        :param opn: The opn of this NetworkInterface.  # noqa: E501
        :type: NamedResource
        """

        self._opn = opn

    @property
    def address(self):
        """Gets the address of this NetworkInterface.  # noqa: E501

        IP address version 4  # noqa: E501

        :return: The address of this NetworkInterface.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this NetworkInterface.

        IP address version 4  # noqa: E501

        :param address: The address of this NetworkInterface.  # noqa: E501
        :type: str
        """

        self._address = address

    @property
    def address_v6(self):
        """Gets the address_v6 of this NetworkInterface.  # noqa: E501

        IP address version 6  # noqa: E501

        :return: The address_v6 of this NetworkInterface.  # noqa: E501
        :rtype: str
        """
        return self._address_v6

    @address_v6.setter
    def address_v6(self, address_v6):
        """Sets the address_v6 of this NetworkInterface.

        IP address version 6  # noqa: E501

        :param address_v6: The address_v6 of this NetworkInterface.  # noqa: E501
        :type: str
        """

        self._address_v6 = address_v6

    @property
    def ip(self):
        """Gets the ip of this NetworkInterface.  # noqa: E501

        IP address  # noqa: E501

        :return: The ip of this NetworkInterface.  # noqa: E501
        :rtype: BaseResource
        """
        return self._ip

    @ip.setter
    def ip(self, ip):
        """Sets the ip of this NetworkInterface.

        IP address  # noqa: E501

        :param ip: The ip of this NetworkInterface.  # noqa: E501
        :type: BaseResource
        """

        self._ip = ip

    @property
    def comment(self):
        """Gets the comment of this NetworkInterface.  # noqa: E501

        Comment  # noqa: E501

        :return: The comment of this NetworkInterface.  # noqa: E501
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """Sets the comment of this NetworkInterface.

        Comment  # noqa: E501

        :param comment: The comment of this NetworkInterface.  # noqa: E501
        :type: str
        """

        self._comment = comment

    @property
    def rev_dns(self):
        """Gets the rev_dns of this NetworkInterface.  # noqa: E501

        RevDNS  # noqa: E501

        :return: The rev_dns of this NetworkInterface.  # noqa: E501
        :rtype: str
        """
        return self._rev_dns

    @rev_dns.setter
    def rev_dns(self, rev_dns):
        """Sets the rev_dns of this NetworkInterface.

        RevDNS  # noqa: E501

        :param rev_dns: The rev_dns of this NetworkInterface.  # noqa: E501
        :type: str
        """

        self._rev_dns = rev_dns

    @property
    def rev_dns_v6(self):
        """Gets the rev_dns_v6 of this NetworkInterface.  # noqa: E501

        RevDNS v6  # noqa: E501

        :return: The rev_dns_v6 of this NetworkInterface.  # noqa: E501
        :rtype: str
        """
        return self._rev_dns_v6

    @rev_dns_v6.setter
    def rev_dns_v6(self, rev_dns_v6):
        """Sets the rev_dns_v6 of this NetworkInterface.

        RevDNS v6  # noqa: E501

        :param rev_dns_v6: The rev_dns_v6 of this NetworkInterface.  # noqa: E501
        :type: str
        """

        self._rev_dns_v6 = rev_dns_v6

    @property
    def subregion(self):
        """Gets the subregion of this NetworkInterface.  # noqa: E501

        Subregion  # noqa: E501

        :return: The subregion of this NetworkInterface.  # noqa: E501
        :rtype: BaseResource
        """
        return self._subregion

    @subregion.setter
    def subregion(self, subregion):
        """Sets the subregion of this NetworkInterface.

        Subregion  # noqa: E501

        :param subregion: The subregion of this NetworkInterface.  # noqa: E501
        :type: BaseResource
        """

        self._subregion = subregion

    @property
    def creation_user(self):
        """Gets the creation_user of this NetworkInterface.  # noqa: E501

        User who created the network interface  # noqa: E501

        :return: The creation_user of this NetworkInterface.  # noqa: E501
        :rtype: UserResource
        """
        return self._creation_user

    @creation_user.setter
    def creation_user(self, creation_user):
        """Sets the creation_user of this NetworkInterface.

        User who created the network interface  # noqa: E501

        :param creation_user: The creation_user of this NetworkInterface.  # noqa: E501
        :type: UserResource
        """

        self._creation_user = creation_user

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NetworkInterface, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NetworkInterface):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, NetworkInterface):
            return True

        return self.to_dict() != other.to_dict()
