# coding: utf-8

"""
    Oktawave API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from pyodk.configuration import Configuration


class RunImportDiskCommand(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'import_disk_id': 'int',
        'tier_id': 'int'
    }

    attribute_map = {
        'import_disk_id': 'ImportDiskId',
        'tier_id': 'TierId'
    }

    def __init__(self, import_disk_id=None, tier_id=None, _configuration=None):  # noqa: E501
        """RunImportDiskCommand - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._import_disk_id = None
        self._tier_id = None
        self.discriminator = None

        self.import_disk_id = import_disk_id
        self.tier_id = tier_id

    @property
    def import_disk_id(self):
        """Gets the import_disk_id of this RunImportDiskCommand.  # noqa: E501

        Id of an imported disk  # noqa: E501

        :return: The import_disk_id of this RunImportDiskCommand.  # noqa: E501
        :rtype: int
        """
        return self._import_disk_id

    @import_disk_id.setter
    def import_disk_id(self, import_disk_id):
        """Sets the import_disk_id of this RunImportDiskCommand.

        Id of an imported disk  # noqa: E501

        :param import_disk_id: The import_disk_id of this RunImportDiskCommand.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and import_disk_id is None:
            raise ValueError("Invalid value for `import_disk_id`, must not be `None`")  # noqa: E501

        self._import_disk_id = import_disk_id

    @property
    def tier_id(self):
        """Gets the tier_id of this RunImportDiskCommand.  # noqa: E501

        Tier id  # noqa: E501

        :return: The tier_id of this RunImportDiskCommand.  # noqa: E501
        :rtype: int
        """
        return self._tier_id

    @tier_id.setter
    def tier_id(self, tier_id):
        """Sets the tier_id of this RunImportDiskCommand.

        Tier id  # noqa: E501

        :param tier_id: The tier_id of this RunImportDiskCommand.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and tier_id is None:
            raise ValueError("Invalid value for `tier_id`, must not be `None`")  # noqa: E501

        self._tier_id = tier_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RunImportDiskCommand, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RunImportDiskCommand):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RunImportDiskCommand):
            return True

        return self.to_dict() != other.to_dict()
